version: '2'
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgresdb:/var/lib/postgresql/data
    - initdb:/docker-entrypoint-initdb.d
  web:
    image: edenb/livemap
    ports:
    - "3000:3000"
    volumes:
    - initdb:/initdb
    - ./overlays:/src/staticlayers:ro
    - ./tracks:/src/tracks:ro
    links:
    - db
    environment:
      C_DB_URL: 'postgres://livemap:livemap@db/livemapdb'
      C_SERVER_PORT: '3000'
      C_FORCESSL: 'false'
      C_MQTT_URL: 'mqtt:///test.mosquitto.org:1883'
      C_MQTT_TOPIC: 'livemap/#'
      C_WCLIENT_NAME: 'Livemap'
      C_WCLIENT_LICENSE: 'MIT'
      C_WCLIENT_ABOUT: 'This is a demo of Livemap'
    restart: always
volumes:
  initdb:
  postgresdb:
